### PR TITLE
fix AttributeError: 'NvidiaDevice' object has no attribute 'cuda_index'

### PR DESCRIPTION
**Pull request by igorvoltaic**
that's my suggestion for [#9](https://github.com/YoRyan/nuxhash/issues/9). it will display cuda index actually.

### CODE REVIEW

**Comment by YoRyan** [comment]
I didn't think it was important to keep the CUDA number. When I start work on the GUI, maybe that will change.

**Comment by YoRyan** [comment]
Ok, I thought about merging this in because future miners might need the CUDA device order, but it turns out the minor number doesn't mean what we think it means. Instead, CUDA programs [use](https://docs.nvidia.com/cuda/cuda-c-programming-guide/#env-vars) a "fastest first" heuristic that you can't really predict the behavior of. So you force them to use the PCI bus ID instead, which we already have.

**Comment by igorvoltaic** [comment]
Not really sure what you mean, but that's what minor_number stands for:

3.2.6. Multi-Device System
[3.2.6.1. Device Enumeration](https://docs.nvidia.com/cuda/cuda-c-programming-guide/#device-enumeration)
A host system can have multiple devices. The following code sample shows how to enumerate these devices, query their properties, and determine the number of CUDA-enabled devices.
```
int deviceCount;
cudaGetDeviceCount(&deviceCount);
int device;
for (device = 0; device < deviceCount; ++device) {
    cudaDeviceProp deviceProp;
    cudaGetDeviceProperties(&deviceProp, device);
    printf("Device %d has compute capability %d.%d.\n",
           device, deviceProp.major, deviceProp.minor);
}
```
here's just my output of nvidia-smi queries:
```shell
[user@localhost ~]$ nvidia-smi --query-gpu=name,pci.bus,index,uuid --format=csv
name, pci.bus, index, uuid
GeForce GTX 1060 6GB, 0x01, 0, GPU-f3da2e71-6e43-729a-e3ae-f731ed96d50c
GeForce GTX 1080 Ti, 0x02, 1, GPU-15ea7bf9-1a0e-2d7f-9c62-c28e5ca1aaf1
GeForce GTX 1060 6GB, 0x03, 2, GPU-3dc4f2b0-6e1b-c088-c342-4367c334795a
GeForce GTX 1060 6GB, 0x09, 3, GPU-03ddeff3-19c4-6676-d02d-6942bd80630d
GeForce GTX 1060 6GB, 0x0A, 4, GPU-ff3318a7-f0dd-dc57-1fb8-cc95ba35c56e
```
```shell
[user@localhost ~]$ nvidia-smi -q | grep UUID -A 1
    GPU UUID                        : GPU-f3da2e71-6e43-729a-e3ae-f731ed96d50c
    Minor Number                    : 0
--
    GPU UUID                        : GPU-15ea7bf9-1a0e-2d7f-9c62-c28e5ca1aaf1
    Minor Number                    : 1
--
    GPU UUID                        : GPU-3dc4f2b0-6e1b-c088-c342-4367c334795a
    Minor Number                    : 2
--
    GPU UUID                        : GPU-03ddeff3-19c4-6676-d02d-6942bd80630d
    Minor Number                    : 3
--
    GPU UUID                        : GPU-ff3318a7-f0dd-dc57-1fb8-cc95ba35c56e
    Minor Number                    : 4
```
```shell
[user@localhost ~]$ nvidia-smi 
Mon Jun 18 17:14:06 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.48                 Driver Version: 390.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  On   | 00000000:01:00.0 Off |                  N/A |
| 90%   65C    P2   111W / 110W |   5450MiB /  6076MiB |     92%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  On   | 00000000:02:00.0 Off |                  N/A |
| 90%   64C    P2   195W / 210W |    808MiB / 11178MiB |     91%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 106...  On   | 00000000:03:00.0 Off |                  N/A |
| 90%   60C    P2    54W / 110W |   1442MiB /  6078MiB |     68%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 106...  On   | 00000000:09:00.0 Off |                  N/A |
| 90%   63C    P2   108W / 110W |   5452MiB /  6078MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   4  GeForce GTX 106...  On   | 00000000:0A:00.0 Off |                  N/A |
| 90%   68C    P2   107W / 110W |   5450MiB /  6078MiB |     99%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1561      C   ...gor/.config/nuxhash/excavator/excavator  5432MiB |
|    0      1716      G   /usr/bin/Xorg                                  5MiB |
|    1      1561      C   ...gor/.config/nuxhash/excavator/excavator   790MiB |
|    1      1716      G   /usr/bin/Xorg                                  5MiB |
|    2      1561      C   ...gor/.config/nuxhash/excavator/excavator  1424MiB |
|    2      1716      G   /usr/bin/Xorg                                  5MiB |
|    3      1561      C   ...gor/.config/nuxhash/excavator/excavator  5434MiB |
|    3      1716      G   /usr/bin/Xorg                                  5MiB |
|    4      1561      C   ...gor/.config/nuxhash/excavator/excavator  5432MiB |
|    4      1716      G   /usr/bin/Xorg                                  5MiB |
+-----------------------------------------------------------------------------+
```

thou... 
```
[user@localhost ~]$ nvidia-smi --help-query-gpu
...
"index"
Zero based index of the GPU. Can change at each boot.
...
```

News for me: it's not safe to use for overclocking :) but think it's okay to use it as reference to `nvidia-smi` output just for the current session one is running.

**Comment by YoRyan** [comment]
The problem is that order is exclusive to nvidia-smi. If you run a CUDA app like ethminer or excavator, the GPU's can (and will) be in a different order.

I would keep the minor number if it told us anything about how those programs would behave because I plan to add other miners eventually, but as we have seen with excavator, they don't correspond.

**Pull request closed without merging**
